# Generated by Django 4.2.16 on 2024-11-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_image_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
