# Generated by Django 4.2.16 on 2024-11-23 20:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_image_description_alter_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/your_cloud_name/image/upload/vdefault_placeholder.jpg', max_length=255, verbose_name='image'),
        ),
    ]
